### ISSUE TITLE
Create optional arguments for Timeout and User Agent

### ISSUE THREAD

**Issue by KyleEvers** [Pascal-0x90/findcdn#10]
# 🚀 Feature Proposal

Define timeout and user agent as global variables that can be overwritten via command line arguments

## Motivation

This will allow the user to modify requests to accommodate slow to domains or domains utilizing a WAF filtering on specific user agents.

## Example
Change:

https://github.com/Pascal-0x90/findCDN/blob/0dd9c6367cbb86c6d6a3af9a74f9f958a58c9e93/src/findCDN/cdnEngine/detectCDN/cdn_check.py#L97-L98

https://github.com/Pascal-0x90/findCDN/blob/0dd9c6367cbb86c6d6a3af9a74f9f958a58c9e93/src/findCDN/cdnEngine/detectCDN/cdn_check.py#L127

To:
```
# Use the --timeout argument to overwrite this value
TIMEOUT = 10

# Use the --user-agent argument to overwrite this value
USER_AGENT = "example user agent"
```

## Pitch
This will make the tool more modular and verbose by accommodating longer timeouts or user agents.

**Comment by DoctorEww** [comment]
findcdn.py is now taking in those as arguments. Now, we need to pass them to the back end.

**Comment by Pascal-0x90** [comment]
Arguments in front end  and back end working as of commit 0fbcc674d946f5b3e32213a541651831b02e0e7e .
